
runtime: custom
env: flex

# Remove the following line if this is the first App Engine service in
# your GCP account.
# service: malware-scanner

env_variables:
  UNSCANNED_BUCKET: unscanned-docs-poc
  CLEAN_BUCKET: scanned-docs-poc
  QUARANTINED_BUCKET: quarantined-docs-poc
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
